### ISSUE TITLE
 events don't submit when offline

### ISSUE THREAD

**Issue by ngoodman** [stuhlmueller/sampleme#3]
Seems to just wait for coming back online to finish the submit script... (On iOS in airplane mode.)

**Comment by ngoodman** [comment]
actually, i think maybe the events get submitted ok (need to verify) the tree just doesn't get collapsed -- maybe that code is on the wrong side of some "success" check?

**Comment by stuhlmueller** [comment]
Yes, there are some user interface issues. The tree needs to be collapsed immediately, with a separate syncing/synced indicator. I'll fix it.

**Comment by stuhlmueller** [comment]
Actually, there may also be a non-ui issue - I see that there was a `Connection timeout. No sockjs heartbeat received.` error earlier today in `insertEvent`. It's also possible that this has to do with the free hosting I'm using at the moment, which is occasionally unreliable.

**Comment by stuhlmueller** [comment]
The UI issue is fixed now, so I'm closing this. Please reopen if there is an additional non-UI issue.
