### ISSUE TITLE
Download CSV

### ISSUE THREAD

**Issue by ngoodman** [stuhlmueller/sampleme#5]
Before seriously using this to track data, I'll want to be able to get out a backup that i can store (and analyze offline). Probably easiest is a csv file of everything in the database? Doing this from command line would be acceptable for now, though if there's already a meteor module to generate a csv from the database, we might as well use it...

**Comment by stuhlmueller** [comment]
The very easiest solution for backup is JSON (should only be a few lines of code to implement).

**Comment by stuhlmueller** [comment]
I added JSON data export in e7f2a19c4e07733308042c476e3242a78c9ff61e.

**Comment by ngoodman** [comment]
awesome! this is better than csv.
